climate:
  - platform: thermostat
    name: "${name} Climate"
    id: ${name}_climate
    visual:
      min_temperature: 10.0
      max_temperature: 45.0
      temperature_step: 0.5
    sensor: room_temperature_zone_1
    min_heating_off_time: 60s
    min_heating_run_time: 60s
    ## remove min_cool_time if not used
    #min_cooling_off_time: 60s
    #min_cooling_run_time: 60s
    min_idle_time: 30s
    heat_action:
      - logger.log:
          format: "Heating"
          level: DEBUG
          tag: climate
    ## remove cool_action if not used
    #cool_action:
    #  - logger.log:
    #      format: "Cooling"
    #      level: DEBUG
    #      tag: climate
    idle_action:
      - logger.log:
          format: "Idle"
          level: DEBUG
          tag: climate