#### 2x EASTRON SDM120 Single phase kWh meter
modbus_controller:
  - id: SDM1
    ## SDM120 meter slaveadress 2
    address: 2
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600
  - id: SDM2
    ## SDM120 meter slaveadress 3
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600

sensor:
    ## Power1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

    ## Power2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    