substitutions:
  name: mitsubishi
  device_description: "Esphome component for Mitsubishi Procon A1M mini with modbus"
  friendly_name: Mitsubishi
  timezone: "Europe/Amsterdam"

# In order to use other language or a different ESP chip, fix include labels file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live (v1 version of my pcb) and esp32s3 is a lilygo ESP32S3-T7 (v2 version of my pcb)
# Be carefull not to upload the wrong code to the wrong chip. This could brick your ESP chip.
packages:
  remote_package:
    url: https://github.com/fonske/Mitsubishi_procon
    ref: main
    refresh: 0s
    files: [ esphome/labels/.procon-labels-en.yaml, 
             esphome/.procon.base.yaml, 
             esphome/boards/board-esp32.yaml 
           ]
      ## Language Packs:
      # esphome/.procon.finder.yaml
      # esphome/labels/.procon-labels-en.yaml
      # esphome/labels/.procon-labels-nl.yaml
      #
      ## Base:
      # esphome/.procon.base.yaml
      #
      ## Boards:
      # esphome/boards/board-esp32.yaml
      # esphome/boards/board-esp32S3.yaml
      # esphome/boards/board-m5stack-atom.yaml
      #
      ## Zone 2, If you have 2 zones on the heatpump enable this:
      # esphome/.procon.zone2.yaml
      #
      ## Climate sensor, only heating (curve, room, flow) is supported at the moment with zone_1:
      # esphome/.procon.climate.yaml
      ## you need to add extra code homeassistant/automations_climate.yaml your automation.yaml in HA directory
      ##
      ## Measuring power and energy
      ## EASTRON 3ph SDM, If you have a 3phase Eastron kWh meter on the heatpump enable this:
      # esphome/.procon.sdm.yaml
      ## set parity to none on the kWh meter. Baudrate to 9600
      ## FINDER 1ph 7E 64 8 230 0210. If you have 2 of these kWh meters on the heatpump enable this:
      # esphome/.procon.finder.yaml
      ## set parity to none on the kWh meter. Baudrate to 9600
      ##

## for developing/testing, uncomment local includes and comment out remote_package part.
#packages:
#  substitutions: !include labels/.procon-labels-nl.yaml
#  device_base1:  !include .procon.base.yaml
##  device_base2:  !include boards/board-esp32.yaml
##  device_base2:  !include boards/board-esp32S3.yaml
##  device_base2:  !include boards/board-m5stack-atom.yaml
#  device_base2:  !include boards/board-m5stack-atoms3-disp.yaml
#  device_base3:  !include .procon.climate.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ## Enable fast wifi connection:
  # fast_connect: on
  ## Enable static IP
  #   manual_ip:
       #static_ip: 192.168.xx.zz
       #gateway: 192.168.xx.1
       #subnet: 255.255.255.0
  
  # uncomment and change when it needs to run on a non .local domain
  #  domain: .local

# Put your API key here if you have one
# api:
#   encryption:
#     key: !secret procon_api_key
